### ISSUE TITLE
Temporary backup of IP (all data for receiving TCP and UDP other protocols) for the included application.

### ISSUE THREAD

**Issue by KenyaLS** [DOWRIGHTTV/dnxfirewall-cmd#3]
### Temporary backup of **IP** (all data for receiving TCP and UDP other protocols) for the included application.
Let's say the application sends IP data over http (

> or TCP over the allowed application

) so that it can be reserved (temporarily) for receiving and further normal operation of the application. Suppose an application is working for me, the ip slot (tcp and UDP) is reserving while the application is running. Since this repository is a console application. This is all given for example. Is it possible to make automatic interaction?

**Comment by DOWRIGHTTV** [comment]
that is an interesting question if i understand it correctly. though it is a "CLI" version, that is moreso regarding the system configurations. it would be fairly difficult to actively monitor connections in terminal and then tell the system to invoke a block on it (for example). primarily just the printing alone would add additional overhead and cause the software to process much slower. that being said, you should be able to input a signature for a specific host while running, and within 10 seconds(the current polling time for file change detection) that host will no longer be allowed for new connections.
